apiVersion: v1
kind: Service
metadata:
  name: event-scraper-py
  labels:
    app: event-scraper-py
spec:
  selector:
    app: event-scraper-py
  ports:
    - name: event-scraper-py
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
